### ISSUE TITLE
Compute: Standard_D* VM sizes missing

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-rest-api-specs#10]
https://github.com/Azure/azure-rest-api-specs/blob/3533959c18b1064219ce95fa6e08a604320a04f9/arm-compute/2015-06-15/swagger/compute.json#L1896-L1917

**Comment by ahmetalpbalkan** [comment]
@singhkay

**Comment by Nepomuceno** [comment]
This was fixed on the pull request 
https://github.com/Azure/azure-rest-api-specs/pull/20
I've signed the clan 3 times already and it does not update

**Comment by ahmetalpbalkan** [comment]
@singhkay can we take care of CLA on #20? I think we can weave this one is not really code.

**Comment by ahmetalpbalkan** [comment]
@devigned @singhkay please help merging #20, the Go SDK is still missing these VM SKUs. We need to keep the specs up to date?
