### ISSUE TITLE
Storage Account API should just validate the specific Subnet being used is Ready while creating multiple storage accounts with subnets in one vnet

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/azure-rest-api-specs#11143]
After tested, seems storage account API would check the Network, which is unrelated (and gets marked as "updating" whenever other subnets change) and throw below error message while creating multiple storage accounts with subnets in one virtual network. I assume Storage Account API should just validate the specific Subnet being used is Ready. So could you help to fix this issue? Thanks.

API Error:
```
Error waiting for Azure Storage Account "xxxxx" to be created: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="NetworkAclsValidationFailure" Message="Validation of network acls failure: SubnetsNotProvisioned:Cannot proceed with operation because subnets xxxxx of the virtual network /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Network/virtualNetworks/xxx are not provisioned. They are in Updating state.."
```

**Comment by blueww** [comment]
@zfchen95 
Would you please help to look at the SRP server issue?

**Comment by magodo** [comment]
ping @zfchen95

**Comment by gro1m** [comment]
@magodo @blueww Has this been resolved in the mean-time?

**Comment by tlaukkanen** [comment]
@gro1m doesn't seem to be resolved yet. Still getting this in 2024:
> Status=400
> Code="NetworkAclsValidationFailure"
> Message="Validation of network acls failure: SubnetsNotProvisioned:Cannot proceed with operation because subnets ... of the virtual network /subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/vnet-... are not provisioned. They are in Updating state.."

**Comment by blueww** [comment]
This is a server issue, please contact server team by raise a help ticket with: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header. Please include more info like the failed request trace (include request ID) to help server team to investigate it.
