### ISSUE TITLE
[MachineLearningServices] The vmSize returned by API is inconsistent with the set value when creating AmlCompute.

### ISSUE THREAD

**Issue by sinbai** [Azure/azure-rest-api-specs#20216]
When creating an AmlCompute with the value of  [vmSize](https://github.com/Azure/azure-rest-api-specs/blob/f842bc69f4c215ad60ffae63ef517c201772f8b2/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/machineLearningServices.json#L3408)  property set to `STANDARD_NC8AS_T4_v3`, the latest version [API](https://github.com/Azure/azure-rest-api-specs/blob/f842bc69f4c215ad60ffae63ef517c201772f8b2/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/machineLearningServices.json#L812) returns the value of vmSize in uppercase as `STANDARD_NC8AS_T4_V3`.

Expected: The vmSize returned by the API should be consistent with the set value(`STANDARD_NC8AS_T4_v3`).

**Comment by navba-MSFT** [comment]
@sinbai Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@sinbai Could you please elaborate on your use case ? Is the `vmSize` property uppercase / lowercase causing any issue ? If yes, what is the issue ?

The compute properties for create AMLcompute operation has the vmsize in uppercase. see [here](https://docs.microsoft.com/en-us/rest/api/azureml/2022-05-01/compute/create-or-update?tabs=HTTP#amlcomputeproperties
). However the [ListVMSizes REST API](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2020-08-01/examples/ListVMSizesResult.json), has it in lower case. Could you check if providing the upper case while creating an AmlCompute works ? This might help in keeping it consistent. Awaiting your reply.

**Comment by sinbai** [comment]
@navba-MSFT thanks for your reply. Case inconsistency caused the resource to be recreated for the terraform user. See [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/17562) for detail.

Per [doc](https://armwiki.azurewebsites.net/rp_onboarding/process/property_design_best_practices.html#keep-readwrite-properties-simple), preserve the casing used on the PUT. Do not normalize the values. (If you need a normalized value in your backend, do not expose it in the API.), so I assume that the `vmSize` property should be case consistent, correct?

**Comment by navba-MSFT** [comment]
@sinbai Thanks for getting back and clarifying the ask. I will look into this further and provide you an update.

**Comment by navba-MSFT** [comment]
@sinbai I am discussing this with the Product Owners and waiting for their update. I will get back to you once I have more details from them.

**Comment by mattmshell** [comment]
Similar to #20336

**Comment by navba-MSFT** [comment]
@sinbai I have heard back from the Product Owners and they did confirm that there is an inconsistency in casing. [ListVMSizes](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2020-08-01/examples/ListVMSizesResult.json) does return the VM size with lowercase letters because the API returns the SKU Name from CRP directly whereas Put Cluster takes the VM size name from AmlCompute’s config file and therefore uses upper case letters. I am following up to see if there are any plans to address this. I will update this thread once I have more details on this.

**Comment by navba-MSFT** [comment]
@sinbai We have created a workitem internally to fix this issue. There is no ETA for the fix now. We will update this thread once the fix is released. Thanks again for reporting this issue.

**Comment by MarkDNL** [comment]
**Issue**
This issue is still triggering destroying and recreation of the requested Azure ML VM and Compute Cluster Instances and Clusters. The latest entry in the issue is more than one year old. 

We have encountered an issue where the `azurerm_machine_learning_compute_cluster` and `azurerm_machine_learning_compute_instance` resource is marked for replacement due to a case sensitivity difference in the `vm_size` property. Even though Azure treats VM sizes in a case-insensitive manner, the Terraform AzureRM provider seems to enforce case sensitivity, causing a drift between the actual state and the desired state as defined in Terraform.

**Issue Details**

The existing `azurerm_machine_learning_compute_cluster` and `azurerm_machine_learning_compute_instance` resources were created with the VM size `STANDARD_DS2_V2`. However, Terraform configuration specifies `Standard_DS2_v2` (note the difference in casing). When running `terraform plan`, Terraform marks the resource for replacement instead of recognizing that the VM sizes are equivalent, leading to unnecessary destruction and recreation of the resources.

* Terraform Version: 3.79.9
* Affected Resource(s): `azurerm_machine_learning_compute_cluster` and `azurerm_machine_learning_compute_instance`

**Expected Behavior**
Terraform should not mark the resource for replacement when the only difference is the casing of the VM size.

**Actual Behavior**
Terraform plans to destroy and replace the entire compute cluster or VM due to a case difference in the VM size attribute.

**Suggested Fixes / Workarounds**
- Ensure that the Terraform comparison operation for the VM size is case-insensitive to align with Azure's behavior.

**Additional Context**
- This issue causes unnecessary downtime and resource re-provisioning, which can be costly and time-consuming, especially with the larger compute clusters. Any advice or workarounds would be greatly appreciated.

Thank you for looking into this issue.
