### ISSUE TITLE
Web Site Extension installation

### ISSUE THREAD

**Issue by vludax** [Azure/azure-rest-api-specs#2819]
As suggested by @hovsepm [here](https://github.com/Azure/azure-libraries-for-net/issues/241#issuecomment-378684495), Azure SDK calls fail to create site extensions when they attempt to PUT a request with null content. Setting request body to an empty JSON object (`{}`) fixes the problem.

**Comment by dsgouda** [comment]
@pavelzel Do you know someone from WebApps who could take a look into this?

**Comment by vludax** [comment]
Also, not sure if this belongs here or in a separate issue, but the returned response code (OK) doesn't seem to match what [generated .NET Azure SDK](https://raw.githubusercontent.com/Azure/azure-sdk-for-net/99834e2e32bf1901a1fa95605416015bf36d682c/src/SDKs/WebSites/Management.Websites/Generated/WebAppsOperations.cs) expects (NoContent).

**Comment by pavelzel** [comment]
@naveedaz Do you know if we've made any updates to the API but haven't yet updated the API spec?

**Comment by vludax** [comment]
It appears that a new issue has come up in the past few days. Now whenever we attempt to install a site extension via Azure .NET SDK, after a PUT /siteextensions request, the SDK generates a GET /siteextensions/<extensionID> request, which returns 404, and ultimately results in a failure of the call to install the site extension.

**Comment by dsgouda** [comment]
@pavelzel @naveedaz any updates here

**Comment by hbuckle** [comment]
@pavelzel @naveedaz - Just hit this issue with the go sdk and resolved in the same way by adding an empty body. Is there any update on resolving it in the specs?

**Comment by tjrobinson** [comment]
@dsgouda @pavelzel @naveedaz I'm still having problems in 2020. Using `api-version=2019-08-01` or `api-version=2018-02-01`. Even with an empty body, or a `{}` body I always get a 400 Bad Request back. This is whether I use PowerShell, Postman, or the [Try It](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/installsiteextension) feature.

[List Site Extensions](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/listsiteextensions) works ok so I'm pretty sure it's not because the rest of my request is invalid (e.g. site name, subscription etc).

**Comment by tjrobinson** [comment]
Thank you for your speedy response!

**Comment by thecodetinker** [comment]
Hello - what was the follow up please? I've just hit this issue some years later. Thanks!

**Comment by jonathan-mcewan** [comment]
Still an issue 6 years on. Can we just all agree that 6 years of stability with sending an empty JSON object (`{}`) is pretty good for Microsoft, and that's the fix for this issue?

**Comment by thecodetinker** [comment]
No problem with that, so long as that's what the specs say (which should then flow through to fixing any downstream issues, IIUC).
